@echo off
echo Checking environment for Emran Ali's Portfolio...

IF NOT EXIST node_modules (
    echo [1/2] node_modules not found. Installing dependencies...
    call npm install
    echo [2/2] Ensuring react-router-dom is present...
    call npm install react-router-dom
) ELSE (
    echo Dependencies already installed. Skipping to start...
)

echo Launching React Development Server...
npm start